version: '3.4'

networks:
  backend:
    name: backend-network

services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=Raiden@2018
        ports:
          - 1433:1433
        networks:
          - backend
    
    #app:
    #    build: .
    #    ports:
    #        - 5000:80
    #    environment:
    #        ASPNETCORE_ENVIRONMENT=Development
    #        ASPNETCORE_URLS=http://0.0.0.0:80
    #        ConnectionStrings__Default=Server=sqlserver,1433;Database=betestdb;User=sa;Password=Raiden@2018
    #    depends_on:
    #      - sqlserver
    #    networks:
    #      - backend
    
    